# Generated by Django 2.2.12 on 2023-07-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(max_length=20, verbose_name='Тип прически')),
                ('price', models.CharField(max_length=4, verbose_name='Цена прически')),
                ('recording_date', models.DateField(max_length=8, verbose_name='Время записи')),
                ('image_barber', models.ImageField(default='default title', upload_to='Hairstyles/', verbose_name='Фотография прически')),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('types_hairstyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair.Hairstyles')),
            ],
        ),
    ]
