# Generated by Django 2.2.12 on 2023-07-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairstyles',
            old_name='image_barber',
            new_name='image_hairs',
        ),
        migrations.RemoveField(
            model_name='hairstyles',
            name='recording_date',
        ),
        migrations.AlterField(
            model_name='hairstyles',
            name='type',
            field=models.TextField(blank=True, max_length=20, verbose_name='Тип прически'),
        ),
    ]
