# Generated by Django 4.2.3 on 2023-07-31 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0003_recors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recors',
            new_name='Records',
        ),
    ]
