# Generated by Django 4.2.3 on 2023-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0004_rename_recors_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='name',
            field=models.TextField(default='title', max_length=24, verbose_name='Ваше имя'),
        ),
    ]
