# Generated by Django 4.2.3 on 2023-08-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0005_records_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='image',
            field=models.ImageField(default='default title', upload_to='images/', verbose_name='Выберите изображение'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя барбера'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='types_hairstyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair.hairstyles', verbose_name='Тип прически'),
        ),
        migrations.AlterField(
            model_name='hairstyles',
            name='image_hairs',
            field=models.ImageField(default='default title', upload_to='Hairstyles/'),
        ),
        migrations.AlterField(
            model_name='records',
            name='name',
            field=models.CharField(default='title', max_length=24, verbose_name='Ваше имя'),
        ),
    ]
