# Generated by Django 4.2.3 on 2023-08-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0006_barber_image_alter_barber_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Выберите изображение'),
        ),
    ]
