# Generated by Django 3.2.16 on 2023-09-07 20:16

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0011_auto_20230907_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='hair.time'),
        ),
    ]
