# Generated by Django 3.2.16 on 2023-09-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0013_rename_time_time_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='times',
            field=models.TextField(max_length=25, verbose_name='Время записи'),
        ),
    ]
