# Generated by Django 4.2.5 on 2023-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0017_auto_20230910_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'verbose_name': 'Дата записи', 'verbose_name_plural': 'Дата записи'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Время записи', 'verbose_name_plural': 'Время записи'},
        ),
        migrations.RenameField(
            model_name='date',
            old_name='date',
            new_name='dates',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address',
            field=models.CharField(max_length=40, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='time',
            name='times',
            field=models.CharField(max_length=25, verbose_name='Время записи'),
        ),
    ]
