# Generated by Django 4.2.5 on 2023-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0018_alter_date_options_alter_time_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='time_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время создания записи'),
        ),
    ]
