# Generated by Django 4.2.5 on 2023-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0021_alter_feedback_options_feedback_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Выберите изображение'),
        ),
    ]
